build: drop AC_FUNC_MALLOC/REALLOC
Two issues with these:
1. They compile & run a test program, which won't work when cross-compiling
2. When libnftnl has just been installed and is not (yet) in linker path, the
test fails since loader won't find libnftnl.

In that case configure will succeed without obvious errors, but config.h
re-defines malloc/realloc with rpl_ prefix, which then results in a
linker error ("undefined reference to `rpl_realloc'") on 'make'.

These macros are only useful to check that malloc(0) returns non-NULL
and that realloc(NULL, ... works.

For nftables the former is irrelevant and the latter a safe assumption,
so lets just remove them.

Signed-off-by: Florian Westphal <fw@strlen.de>